addin formik
IbrahimQumseya/task-managment pull request #7
Opened 2022-03-01 15:58 UTC by IbrahimQumseya

2022-03-03 20:59 UTC, sergiutoma commented
![missing-dependencys](https://user-images.githubusercontent.com/77193627/156652034-e5030373-a50a-485f-a713-5b5a4b4e495d.PNG)

2022-03-03 21:11 UTC, IbrahimQumseya commented
i think we need just `npm i`

2022-03-08 07:36 UTC, sergiutoma requested changes
- It should only redirect us to **/login** if the sign-up was successful made.
- The sign-up button should be disabled if terms has not been checked
- The terms button does not open any dialog with the terms to be accepted
- `formik` and `yup` libraries must be installed in the project.(`npm i -S formik yup`)

2022-03-08 07:36 UTC, sergiutoma commented on src/screens/SignUp.js
> +    const { email, lastName, firstName, password, passwordConform, username } = values;
Is it a reason to deconstruct and then rebuild the object(allData)?

2022-03-13 09:45 UTC, sergiutoma approved these changes
Looks good! Maybe we can add preview terms in the future. 👍

2022-03-13 12:34 UTC, merged